name: Quilt Patch Codegen

on:
  push:
    branches: [main]
    paths:
      - "part2/quilt/**"

jobs:
  codegen:
    runs-on: ubuntu-latest

    permissions:
      # need 'write' to commit + push
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: run patch codegen
        run: |
          cd part2/quilt
          python patch.py

        # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
        commit_message: "patch codegen"
